---

- name: Install cfssl_extra_packages
  ansible.builtin.pkgng:
    name: "{{ cfssl_extra_packages }}"

- name: Install cfssl
  ansible.builtin.pkgng:
    name: "{{ cfssl_package }}"
    state: present

- name: Create cfssl_group
  ansible.builtin.group:
    name: "{{ cfssl_group }}"

- name: Create cfssl_user
  ansible.builtin.user:
    name: "{{ cfssl_user }}"
    group: "{{ cfssl_group }}"

- name: Create /etc/rc.conf.d/cfssl when cfssl_db_type is not empty
  ansible.builtin.template:
    src: FreeBSD.rc.j2
    dest: /etc/rc.conf.d/cfssl
    mode: "0644"
  when:
    - cfssl_db_type | length > 0
  notify:
    - Restart cfssl

- name: Enable cfssl_service when cfssl_db_type is not empty
  ansible.builtin.service:
    name: "{{ cfssl_service }}"
    enabled: yes
  when:
    - cfssl_db_type | length > 0
