---

- name: Install cfssl_extra_packages
  pkgng:
    name: "{{ cfssl_extra_packages }}"

- name: Install cfssl
  pkgng:
    name: "{{ cfssl_package }}"
    state: present

- name: Create cfssl_group
  group:
    name: "{{ cfssl_group }}"

- name: Create cfssl_user
  user:
    name: "{{ cfssl_user }}"
    group: "{{ cfssl_group }}"
