---

- name: Install cfssl_extra_packages
  community.general.openbsd_pkg:
    name: "{{ cfssl_extra_packages }}"

- name: Install cfssl
  community.general.openbsd_pkg:
    name: "{{ cfssl_package }}"
    state: present

- name: Create cfssl_group
  ansible.builtin.group:
    name: "{{ cfssl_group }}"

- name: Create cfssl_user
  ansible.builtin.user:
    name: "{{ cfssl_user }}"
    group: "{{ cfssl_group }}"
